language: node_js
node_js:
  - '12'
install:
  - npm install -g codecov nyc npx
  - npm install

script:
  - npm run lint
  - npm test

after_success:
  - npm run report-coverage
  
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx -p node@8 -c "npm run semantic-release"